### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by powellchristoph** [mattolenik/hclq#14]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

It looks like your install script doesn't take the architecture of the platform into account when determining the download url and returns all three urls for the `curl`.

```
Installing /usr/local/bin/hclq
curl: (3) Illegal characters found in URL
```

The `curl` command that is constructed is:
`curl  --progress-bar -JLo "/usr/local/bin/hclq" "https://github.com/mattolenik/hclq/releases/download/0.5.3/hclq-linux-386
https://github.com/mattolenik/hclq/releases/download/0.5.3/hclq-linux-amd64
https://github.com/mattolenik/hclq/releases/download/0.5.3/hclq-linux-arm"`

**Comment by mattolenik** [comment]
Thanks for pointing this out! I might try to write a test to cover the install script as well.

**Comment by mattolenik** [comment]
Hey @powellchristoph, I've updated the script to account for this. It should detect architecture automatically, but there is also the `-d` option to force it. Let me know if it works for you. I was only able to test it on Linux and macOS machines so far, but it should work on most modern POSIX systems.

The readme has been updated with install script details as well.
