### ISSUE TITLE
Can you move the readAll call on cmd and use bytes on queryHCL

### ISSUE THREAD

**Issue by sebglon** [mattolenik/hclq#2]
To easily reuse go code as lib, can you move the reader param on method `func HCL(reader io.Reader, qry *Query) (results []Result, isList bool, node *ast.File, err error)` by bytes.

THis is more easy to reuse your lib on another Go project.

readAll is a stream and can be call only once. after the reader content is empty.

**Comment by mattolenik** [comment]
Sorry for the late response! The recent changes in the 0.5.x releases should make using hclq as a library _much_ easier. The API isn't necessarily final but it is easy enough to work with at the moment. Feedback on it much appreciated!
