### ISSUE TITLE
`set` command is not working if terraform list is empty (Available PR)

### ISSUE THREAD

**Issue by LudovicTOURMAN** [mattolenik/hclq#4]
Using this terraform sample `bar.tf`:
```terraform
module "bar" {
  source = "../modules/foo"
  my_list = []
}
```
Running command `cat bar.tf | hclq set 'module.bar.my_list[]' '["foo","bar"]'` will result in not changing the value in the file/output.

This is caused by the fact that list is empty and we don't return a `Result` struct containing the concerned ast.Node

**Comment by mattolenik** [comment]
Hey, thank you for the PR, and sorry for the crazy late response! I didn't have time to maintain this project for a little while but it recently underwent a huge refactor. This and other, similar issues should all be fixed now. I'm sorry I didn't notice your PR sooner :( but it is appreciated!

**Comment by LudovicTOURMAN** [comment]
Hi Matt,

Thanks for the answer. I'll have a look to the refacto ;)
